[versions]
jwt = "0.11.5"
flywayPostgres = "10.22.0"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
snakeyaml = { module = "org.yaml:snakeyaml" }

jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jwt" }

postgresql = { module = "org.postgresql:postgresql" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flywayPostgres" }

[bundles]
commonRuntimeLibs = [
    "logback-classic",
    "jackson-module-kotlin",
    "snakeyaml"
]

securityRuntimeLibs = [
    "jjwt-impl",
    "jjwt-jackson"
]

dbRuntimeLibs = [
    "postgresql",
    "flyway-database-postgresql"
]
