[libraries]
micronaut-test-junit5 = { module = "io.micronaut.test:micronaut-test-junit5" }
postgresql = { module = "org.testcontainers:postgresql" }
testcontainers = { module = "org.testcontainers:testcontainers" }
kotlin-faker = { module = "io.github.serpro69:kotlin-faker", version = "1.13.0" }
aws-sdk-ecr = { module = "aws.sdk.kotlin:ecr" }

[bundles]
testImplementationLibs = [
    "micronaut-test-junit5",
    "postgresql",
    "testcontainers",
    "kotlin-faker",
    "aws-sdk-ecr"
]
