---
env.db.schema: public
---
#tag::logging[]
logger:
  levels:
    net.blugrid.api: DEBUG
#end::logging[]
---
#tag::swagger[]
micronaut.openapi.enabled: false
micronaut.openapi.swagger.file.generation.enabled: false
---
#tag::endpoints[]
endpoints:
  all:
    enabled: false
#end::endpoints[]
---
#tag::security[]
#micronaut:
#  security:
#    enabled: true
#    authentication: bearer
#    intercept-url-map:
#      - pattern: "/**"
#        access:
#          - isAuthenticated()
#    token:
#      enabled: true
#      roles-name: "roles"
#      jwt:
#        enabled: true
#        signatures:
#          jwks:
#            auth0:
#              url: "https://bizkinetics.au.auth0.com/.well-known/jwks.json"
#end::security[]
---
#tag::client[]
micronaut:
  http:
    client:
      read-timeout: 300s
  services:
    localhost:
      url: http://localhost
#  security:
#    oauth2:
#      clients:
#        auth0:
#          client-id: '${OAUTH_CLIENT_ID:REDACTED_CLIENT_ID}'
#          client-secret: '${OAUTH_CLIENT_SECRET:REDACTED_CLIENT_SECRET}'
#          grant-type: 'client_credentials'
#          token:
#            url: '${OAUTH_TOKEN_URL:`https://bizkinetics.au.auth0.com/oauth/token`}'
#            auth-method: 'client_secret_post'
#          client-credentials:
#            service-id-regex: '.*'
#            additional-request-params:
#              audience: '${AUTH0_API_IDENTIFIER:`https://dev.bizkinetics.com.au/api/rest`}'
#end::client[]
