env.db.schema: public

logger:
  levels:
    net.blugrid.api: DEBUG

micronaut.openapi.enabled: false
micronaut.openapi.swagger.file.generation.enabled: false

endpoints:
  all:
    enabled: false

micronaut:
  http:
    client:
      read-timeout: 300s
  services:
    localhost:
      url: http://localhost
