logging:
  level:
    com.github.dockerjava: WARN
    io.micronaut.data: DEBUG
    io.micronaut.http: DEBUG
    io.micronaut.security: DEBUG
    io.micronaut: INFO
    net.blugrid: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    testcontainers: INFO
