micronaut:
  server:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSX"
  serde:
    inclusion: NON_NULL
    write-dates-as-timestamps: false
    write-durations-as-timestamps: false

jackson:
  serialization:
    write-bigdecimal-as-plain: true
    write-date-timestamps-as-nanoseconds: false
    write-dates-as-timestamps: false
    write-enums-using-to-string: true
    write_numbers_as_strings: true

  deserialization:
    read-date-timestamps-as-nanoseconds: false
    read-enums-using-to-string: true
